version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - testnet
    depends_on:
      - db
      - php
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        user: ${USER:-defaultuser}
        uid: ${UID:-1000}
        gid: ${GID:-1000}
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - testnet
  db:
    image: mariadb:10.9.2
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: albert
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    networks:
      - testnet  
  node:
    image: node:19.6
    container_name: node
    ports:
      - 80:80
    volumes: 
      - ./frontend:/var/www/html
    working_dir: /var/www/html
    user: ${UID:-1000}:${GID:-1000}
    command: npm run dev
    networks:
      - testnet
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    links: 
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    depends_on: 
      - db
    networks:
      - testnet
networks:
  testnet:
    driver: bridge